[project]
name = "scp-obsidian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "libzim>=3.7.0",
    "tqdm>=4.67.1",
]
